apiVersion: v1
kind: Pod
metadata:
  name: ganeshnginx2
  namespace: development
  labels: 
    app: ganenginx
spec:
 containers:
   - name: nginxcontainer1
     image: nginx
     resources:
       requests:
         cpu: 1
         memory: 1Gi
       limits:
         cpu: 1
         memory: 1Gi

---

apiVersion: v1
kind: Service
metadata:
  name: nginxservice
  labels:
    app: ganengnix
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: ganengnix
